language: nix

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

cache:
  directories:
    - $HOME/.stack
    - /nix/store

before_install:
  - nix-env -i stack

script:
  - stack --version | head -n 1
  - stack --nix --no-nix-pure --no-terminal test

notifications:
  email: false
