# Site settings
title: Chris Martin
description: "Card for Coin, Scala, Haskell, complaining"
baseurl: ""
url: "http://chris-martin.org"
email: ch.martin@gmail.com
twitter_username: chris__martin
github_username: chris-martin
stackoverflow_userid: 402884
googleplus_userid: 102949496905033075906
facebook_username: ch.martin

# Build settings
markdown: kramdown
permalink: /:year/:title
timezone: UTC

gems:
  - jekyll-redirect-from
