resolver: lts-9.6

packages:
  - bricks
  - bricks-internal
  - bricks-internal-test
  - bricks-parsec
  - bricks-rendering
  - bricks-syntax

extra-deps:
  - either-list-functions-0.0.0.1

nix:
  packages:
    - glibcLocales
