resolver: nightly-2017-10-25

packages:
  - bricks
  - bricks-internal
  - bricks-internal-test
  - bricks-parsec
  - bricks-rendering
  - bricks-syntax

extra-deps:
  - loc-0.1.3.1
  - path-text-utf8-0.0.0.2
