name: chris-martin-org
version: 0.1.0.0
license: Apache-2.0
github: chris-martin/chris-martin.org

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - ChrisMartinOrg
    - ChrisMartinOrg.CommandLineOpts
    - ChrisMartinOrg.Content
    - ChrisMartinOrg.Core
    - ChrisMartinOrg.Css
    - ChrisMartinOrg.Hash
    - ChrisMartinOrg.Home
    - ChrisMartinOrg.NixLike
    - ChrisMartinOrg.Post
    - ChrisMartinOrg.PostDate
    - ChrisMartinOrg.Post.Page
    - ChrisMartinOrg.Post.Parse
    - ChrisMartinOrg.Redirect

dependencies:
  - attoparsec
  - base
  - base16-bytestring
  - blaze-html
  - blaze-markup
  - bytestring
  - containers
  - cryptonite
  - directory
  - filepath
  - highlighting-kate
  - hsass
  - markdown
  - memory
  - optparse-applicative
  - parsec
  - safe
  - text
  - time
  - unix

executables:
  chris-martin-org:
    source-dirs: app
    main: Main.hs
    dependencies:
      - chris-martin-org

tests:
  doctest:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - base
      - chris-martin-org
      - doctest
