name: bricks-internal-test
version: 0.0.0.4
github: chris-martin/bricks

synopsis: |
  ...

description: |
  ...

category: Language

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license: Apache-2.0
license-file: license.txt

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Bricks.Test.Hedgehog
    - Bricks.Test.QQ

dependencies:

  - bricks-internal

  - base             >= 4.9   && < 4.11
  - containers       >= 0.5.7 && < 0.6
  - hedgehog         >= 0.5   && < 0.6
  - template-haskell >= 2.2   && < 2.13
  - text             >= 1.2.2 && < 1.3
