name: bricks
version: 0.0.0.3
github: chris-martin/bricks

synopsis: |
  Bricks is a lazy functional language based on Nix.

description: |
  Bricks is a lazy functional language based on Nix.
  This package provides parsing, rendering, and
  evaluation for the Bricks language.

category: Language

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license: Apache-2.0
license-file: license.txt

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:

    - Bricks

    - Bricks.BuiltinFunctions
    - Bricks.Evaluation
    - Bricks.ExpressionToTerm
    - Bricks.Prelude
    - Bricks.Term
    - Bricks.Type

    - Bricks.Internal.Monad

dependencies:

  - bricks-internal
  - bricks-parsec
  - bricks-rendering
  - bricks-syntax

  - base       >= 4.9   && < 4.10
  - containers >= 0.5.7 && < 0.6
  - mtl
  - parsec     >= 3.1.6 && < 3.2
  - path
  - path-text-utf8
  - text       >= 1.2.2 && < 1.3
  - transformers

tests:

  doctest:
    source-dirs: test
    main: doctest.hs
    ghc-options:
      - -threaded
    dependencies:
      - base    >= 4.9  && < 4.10
      - doctest >= 0.11 && < 0.14

  evaluation:
    source-dirs: test
    main: evaluation.hs
    ghc-options:
      - -threaded
    dependencies:
      - bricks
      - bricks-internal-test
      - base             >= 4.9 && < 4.10
      - hedgehog         >= 0.5 && < 0.6
      - template-haskell >= 2.2 && < 2.12
