name: bricks
version: 0.1.0.0
license: Apache-2.0
github: chris-martin/bricks

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules:
    - ChrisMartinOrg.NixLike

dependencies:
  - base
  - parsec
  - text

tests:
  doctest:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - base
      - bricks
      - doctest
