name: bricks
version: 0.1.0.0
license: Apache-2.0
github: chris-martin/bricks

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Bricks
    - Bricks.Identifiers
    - Bricks.Keywords
    - Bricks.Parsing
    - Bricks.Rendering
    - Bricks.Types

dependencies:
  - base
  - parsec
  - text

tests:

  rendering:
    source-dirs: test
    main: rendering.hs
    ghc-options:
      - -Wno-missing-signatures
      - -threaded
    dependencies:
      - base
      - bricks
      - hedgehog
      - template-haskell

  parsing:
    source-dirs: test
    main: parsing.hs
    ghc-options:
      - -Wno-missing-signatures
      - -threaded
    dependencies:
      - base
      - bricks
      - hedgehog
      - template-haskell
