name: bricks
version: 0.0.0.1
license: Apache-2.0
license-file: license.txt
github: chris-martin/bricks

synopsis: Bricks is a lazy functional language based on Nix.

description: |
  Bricks is a lazy functional language based on Nix.
  This package provides parsing, rendering, and
  evaluation (forthcoming) for the Bricks language.

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:

    - Bricks

    - Bricks.Expression
    - Bricks.Expression.Construction
    - Bricks.IndentedString
    - Bricks.Keyword
    - Bricks.Parsing
    - Bricks.Rendering
    - Bricks.UnquotedString

    - Bricks.Internal.Functor
    - Bricks.Internal.Prelude
    - Bricks.Internal.Seq
    - Bricks.Internal.Text

dependencies:
  - base
  - containers
  - parsec
  - text

tests:

  doctest:
    source-dirs: test
    main: doctest.hs
    ghc-options:
      - -threaded
    dependencies:
      - base
      - bricks
      - doctest

  rendering:
    source-dirs: test
    main: rendering.hs
    ghc-options:
      - -threaded
    dependencies:
      - base
      - bricks
      - hedgehog
      - template-haskell

  parsing:
    source-dirs: test
    main: parsing.hs
    ghc-options:
      - -threaded
    dependencies:
      - base
      - bricks
      - hedgehog
      - template-haskell
