name: bricks-syntax
version: 0.0.0.4
github: chris-martin/bricks

synopsis: |
  ...

description: |
  ...

category: Language

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license: Apache-2.0
license-file: license.txt

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Bricks.Expression
    - Bricks.Expression.Construction
    - Bricks.Keyword
    - Bricks.Source
    - Bricks.UnquotedString

dependencies:

  - bricks-internal

  - base       >= 4.9   && < 4.11
  - containers >= 0.5.7 && < 0.6
  - either-list-functions == 0.0.0.2
  - text       >= 1.2.2 && < 1.3

data-files:
  - test-data/expression-show-examples.txt

tests:

  doctest:
    source-dirs: test
    main: doctest.hs
    ghc-options:
      - -threaded
    dependencies:
      - base    >= 4.9  && < 4.11
      - doctest >= 0.11 && < 0.14

  show:
    source-dirs: test
    main: show.hs
    dependencies:
      - bricks-syntax
      - base    >= 4.9  && < 4.11
      - exceptions
      - hint
